### ISSUE TITLE
Please provide installation/usage instructions

### ISSUE THREAD

**Issue by rnauber** [OinkIguana/Catan#1]
Hi there,
as a total nodejs rookie, I would really like to have foolproof installation instructions for this app. What I tried up until now is:

`npm install https://github.com/OinkIguana/machi-koro.git`

```
bash-4.4$ npm start

> machi-koro@1.0.0 start /data/data/com.termux/files/home/node_modules/machi-koro
> node server.js

module.js:471
    throw err;
    ^

Error: Cannot find module '/data/data/com.termux/files/home/node_modules/machi-koro/server.js'
    at Function.Module._resolveFilename (module.js:469:15)
    at Function.Module._load (module.js:417:25)
    at Module.runMain (module.js:604:10)
    at run (bootstrap_node.js:390:7)
    at startup (bootstrap_node.js:150:9)
    at bootstrap_node.js:505:3

npm ERR! Linux 3.4.0-perf-gc14c2d5
npm ERR! argv "/data/data/com.termux/files/usr/bin/node" "/data/data/com.termux/files/usr/bin/npm" "start"
npm ERR! node v6.10.3
npm ERR! npm  v3.10.10
npm ERR! code ELIFECYCLE
npm ERR! machi-koro@1.0.0 start: `node server.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the machi-koro@1.0.0 start script 'node server.js'.
```

and

```
bash-4.4$ ./node_modules/.bin/webpack --config node_modules/machi-koro/webpack.config.js 
Invalid configuration object. Webpack has been initialised using a configuration object that does not match the API schema.
 - configuration[0].output.path: The provided value "./public_html" is not an absolute path!
 - configuration[1].output.path: The provided value "./" is not an absolute path!

```

Thank you,
Richard

**Comment by rnauber** [comment]
Sorry, wrong app...
